
name = "image-rotation"
account_id = "eec00739050a8a4cbf359a1dedb8cad3"
workers_dev = true
compatibility_date = "2023-11-20"
main = "worker.js" # Entry point

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[env.production]
FALLBACK_IMAGE = "/images/background.jpg"
kv_namespaces = [
  { binding = "KV_STORE", id = "4ea68035cab04a258a979cc1d02df30f"}
]

